name: Acceptor Test
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

  repository_dispatch:
    types: [ Test-Dispatch ]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        # normally you would write
        # uses: cypress-io/github-action@v6
        uses: ./
        with:
          working-directory: e2e/1-getting-started
          component: true