name: Test Automation Run

on: [push]

#   repository_dispatch:
#     types: [ Test-Dispatch ]

jobs:
  test:
    name: Test Automation Run
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix: 
        specFile:
          - cypress/e2e/1-getting-started/*
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress Test run
        uses: cypress-io/github-action@v4
        with:
          group: 'Test Automation Run'
          spec: ${{ matrix.specFile }}
